server:
 port: 9002
spring:
 application:
   name: ihrm-system #指定服务名
 datasource:
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://localhost:3306/ihrm?useUnicode=true&characterEncoding=utf8
   username: root
   password: 1234
 jpa:
   database: MySQL
   show-sql: true
   open-in-view: true
   hibernate:
     ddl-auto: update
   database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
 redis:
   host: 127.0.0.1
   port: 6379
jwt:
 config:
    key: saas-ihrm
    ttl: 360000
#微服务注册到eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
ai:
  appId: 19634940
  apiKey: 2cik8dDMSHxLbdFSEnaWXhTm
  secretKey: Y28m4PFuTqufWAGvvMGGC8Wmarzw6SLw
  imageType: BASE64
  groupId: ihrm
qr:
  url: http://127.0.0.1:8080/#/facelogin