server:
 port: 9002
spring:
 application:
   name: ihrm-system #指定服务名
 datasource:
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://localhost:3306/ihrm?useUnicode=true&characterEncoding=utf8
   username: root
   password: 1234
 jpa:
   database: MySQL
   show-sql: true
   open-in-view: true
   hibernate:
     ddl-auto: update
   database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
 redis:
   host: 127.0.0.1
   port: 6379
jwt:
 config:
    key: saas-ihrm
    ttl: 360000
